<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE contributors
[
<!ELEMENT name (first?, middle?, last)>
<!ELEMENT contributors (introduction, name+)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT introduction (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
]
>

<contributors>
  <introduction>
  These are some of the many people who have helped with this Ant Library.
  </introduction>
  <name>
    <first>Alexey</first>
    <last>Solofnenko</last>
  </name>
  <name>
    <first>Antoine</first>
    <last>Levy-Lambert</last>
  </name>
  <name>
    <first>Brian</first>
    <last>Watson</last>
  </name>
  <name>
    <first>Conor</first>
    <last>MacNeill</last>
  </name>
  <name>
    <first>Dave</first>
    <last>Brosius</last>
  </name>
  <name>
    <first>Martijn</first>
    <last>Kruithof</last>
  </name>
  <name>
    <first>Mike Schilling</first>
    <last>Kruithof</last>
  </name>
  <name>
    <first>Peter</first>
    <last>Donald</last>
  </name>
  <name>
    <first>Peter</first>
    <last>Reilly</last>
  </name>
  <name>
    <first>Stefan</first>
    <last>Bodewig</last>
  </name>
  <name>
    <first>Stephane</first>
    <last>Bailliez</last>
  </name>
  <name>
    <first>Steve</first>
    <last>Loughran</last>
  </name>
</contributors>